# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run the gemspec command
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = %q{sequel_simple_callbacks}
  s.version = "0.1.1"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["tadman"]
  s.date = %q{2010-08-25}
  s.description = %q{This plugin makes it possible to declare simple before and after callbacks on the class level just like ActiveRecord}
  s.email = %q{github@tadman.ca}
  s.extra_rdoc_files = [
    "LICENSE",
     "README.rdoc"
  ]
  s.files = [
    ".document",
     ".gitignore",
     "LICENSE",
     "README.rdoc",
     "Rakefile",
     "VERSION",
     "lib/sequel_simple_callbacks.rb",
     "sequel_simple_callbacks.gemspec",
     "test/helper.rb",
     "test/models/conditional.rb",
     "test/models/example.rb",
     "test/models/model_triggers.rb",
     "test/test_sequel_simple_callbacks.rb"
  ]
  s.homepage = %q{http://github.com/tadman/sequel_simple_callbacks}
  s.rdoc_options = ["--charset=UTF-8"]
  s.require_paths = ["lib"]
  s.rubygems_version = %q{1.3.7}
  s.summary = %q{Sequel Plugin to add ActiveRecord style callback declarations}
  s.test_files = [
    "test/helper.rb",
     "test/models/conditional.rb",
     "test/models/example.rb",
     "test/models/model_triggers.rb",
     "test/test_sequel_simple_callbacks.rb"
  ]

  if s.respond_to? :specification_version then
    current_version = Gem::Specification::CURRENT_SPECIFICATION_VERSION
    s.specification_version = 3

    if Gem::Version.new(Gem::VERSION) >= Gem::Version.new('1.2.0') then
      s.add_development_dependency(%q<sequel>, [">= 0"])
    else
      s.add_dependency(%q<sequel>, [">= 0"])
    end
  else
    s.add_dependency(%q<sequel>, [">= 0"])
  end
end

